# Generated by Django 6.0.3 on 2026-03-27 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('royal', 'القاعة الملكية'), ('diamond', 'القاعة الماسية')], max_length=20, unique=True, verbose_name='اسم القاعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'قاعة',
                'verbose_name_plural': 'القاعات',
            },
        ),
        migrations.CreateModel(
            name='OccasionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wedding', 'فرح إسلامي'), ('contract', 'كتب كتاب'), ('condolence', 'عزاء'), ('aqeeqa', 'عقيقة'), ('meeting', 'اجتماعات عمل')], max_length=30, unique=True, verbose_name='نوع المناسبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'نوع مناسبة',
                'verbose_name_plural': 'أنواع المناسبات',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hall_rental', 'إيجار القاعة'), ('decoration', 'ديكور'), ('zaffa', 'زفة'), ('photography', 'تصوير'), ('beverages', 'مشروبات'), ('meals', 'وجبات')], max_length=30, unique=True, verbose_name='اسم الخدمة')),
                ('service_type', models.CharField(choices=[('main', 'خدمة رئيسية'), ('extra', 'خدمة إضافية')], max_length=10, verbose_name='نوع الخدمة')),
                ('is_hall_based', models.BooleanField(default=False, verbose_name='سعرها يختلف حسب القاعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
            },
        ),
        migrations.CreateModel(
            name='FixedServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الثابت')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_price', to='core.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'سعر ثابت',
                'verbose_name_plural': 'أسعار ثابتة',
            },
        ),
        migrations.CreateModel(
            name='MainServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='core.hall', verbose_name='القاعة')),
                ('occasion_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='core.occasiontype', verbose_name='نوع المناسبة')),
            ],
            options={
                'verbose_name': 'سعر إيجار',
                'verbose_name_plural': 'أسعار الإيجار',
                'unique_together': {('hall', 'occasion_type')},
            },
        ),
        migrations.CreateModel(
            name='ExtraServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_prices', to='core.hall', verbose_name='القاعة')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall_prices', to='core.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'سعر خدمة إضافية',
                'verbose_name_plural': 'أسعار الخدمات الإضافية',
                'unique_together': {('service', 'hall')},
            },
        ),
    ]
