# Generated by Django 6.0.3 on 2026-03-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mainserviceprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mainserviceprice',
            name='duration_type',
            field=models.CharField(choices=[('1h', 'ساعة'), ('2h', 'ساعتان'), ('na', 'غير مرتبط بمدة')], default='na', max_length=5, verbose_name='المدة'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='اسم الخدمة'),
        ),
        migrations.AlterUniqueTogether(
            name='mainserviceprice',
            unique_together={('hall', 'occasion_type', 'duration_type')},
        ),
    ]
