# Generated by Django 6.0.3 on 2026-03-27 08:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف مصري صحيح', regex='^01[0125]\\d{8}$')], verbose_name='رقم الهاتف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='تاريخ الحجز')),
                ('occasion_date', models.DateField(verbose_name='تاريخ المناسبة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'منتهي')], default='pending', max_length=15, verbose_name='حالة الحجز')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي السعر')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.hall', verbose_name='القاعة')),
                ('occasion_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.occasiontype', verbose_name='نوع المناسبة')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-occasion_date'],
                'unique_together': {('hall', 'occasion_date')},
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='الكمية')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bookings.booking', verbose_name='الحجز')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'خدمة في الحجز',
                'verbose_name_plural': 'خدمات الحجز',
            },
        ),
    ]
