# Generated by Django 6.0.3 on 2026-03-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_type',
            field=models.CharField(choices=[('1h', 'ساعة'), ('2h', 'ساعتان')], default='1h', max_length=10, verbose_name='مدة الحجز'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hall_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر القاعة'),
        ),
        migrations.AddField(
            model_name='booking',
            name='services_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الخدمات'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الوحدة'),
        ),
    ]
