# Generated by Django 6.0.3 on 2026-04-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_unique_together_booking_duration_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bride_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان العروسة'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bride_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم العروسة'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bride_national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='الرقم القومي للعروسة'),
        ),
        migrations.AddField(
            model_name='booking',
            name='groom_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان العريس'),
        ),
        migrations.AddField(
            model_name='booking',
            name='groom_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم العريس'),
        ),
        migrations.AddField(
            model_name='booking',
            name='groom_national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='الرقم القومي للعريس'),
        ),
    ]
